@BlogApi2_backend_HostAddress = http://localhost:5233

GET {{BlogApi2_backend_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json

###
GET {{BlogApi2_backend_HostAddress}}/api/Blog/20
Accept: application/json

###
POST {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json
Content-Type: application/json

{
  "Title": "Gossip girl",
  "Content": "This is the content of the blog post.",
  "AuthorId": 9
}
###
POST {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json
Content-Type: application/json

{
  "Title": "fashion 2025",
  "Content": "In this blog, we will explore emerging trends in technology that are shaping the future.",
  "AuthorId": 8
}

###
GET {{BlogApi2_backend_HostAddress}}/api/Blog/15
Accept: application/json

###
GET {{BlogApi2_backend_HostAddress}}/api/Author
Accept: application/json

###
POST {{BlogApi2_backend_HostAddress}}/api/Author
Content-Type: application/json
Accept: application/json

{
  "Name": "Jane Doe",
  "Email": "janedoe@example.com",
  "Password":"revvity@123"
}
###
POST {{BlogApi2_backend_HostAddress}}/api/Author
Content-Type: application/json
Accept: application/json

{
  "Name": "Emily Johnson",
  "Email": "emily.johnson@example.com"
}


###
POST {{BlogApi2_backend_HostAddress}}/api/Author
Content-Type: application/json
Accept: application/json

{
  "Name": "Sarah Lee",
  "Email": "sarah.lee@domain.org"
}


###
POST {{BlogApi2_backend_HostAddress}}/api/Author
Content-Type: application/json
Accept: application/json

{
  "Name": "John Smith",
  "Email": "johnsmith@example.com"
}

###
POST {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json
Content-Type: application/json

{
  "Title": "2025 Fashion Trends You Need to Know",
  "Content": "A sneak peek into the latest fashion trends and how you can incorporate them into your wardrobe.",
  "AuthorId": 4
}

###
POST {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json
Content-Type: application/json

{
  "Title": "How to Stay Productive While Working from Home",
  "Content": "Here are some strategies to maintain focus and productivity when working remotely.",
  "AuthorId": 2
}

###
POST {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json
Content-Type: application/json

{
  "Title": "How to Stay Productive While Working from Home and chill as well",
  "Content": "Here are some strategies to maintain focus and productivity when working remotely.",
  "AuthorId": 2
}

###
POST {{BlogApi2_backend_HostAddress}}/api/Blog
Accept: application/json
Content-Type: application/json

{
  "Title": "Top 25 Destinations to Visit in 2025 in india",
  "Content": "Explore the most popular travel destinations for 2025 and why they should be on your bucket list.",
  "AuthorId": 9
}


###
PUT {{BlogApi2_backend_HostAddress}}/api/Blog/1
Accept:  application/json
Content-Type: application/json

{
  "Title": "Updated Blog Title",
  "Content": "This is the updated content of the blog.",
  "AuthorId": 9
}

###
DELETE {{BlogApi2_backend_HostAddress}}/api/Blog/2
Accept: application/json


 
###
POST {{BlogApi2_backend_HostAddress}}/api/Author/login
Accept: application/json
Content-Type: application/json

{
    "email":"janedoe@example.com",
    "password":"revvity@123"
}

###
POST {{BlogApi2_backend_HostAddress}}/api/Author/register
Content-Type: application/json
Accept: application/json

{
  "Name": "John Smith",
  "Email": "charliesmith@example.com",
  "Password": "securePassword123"
}


###
GET {{BlogApi2_backend_HostAddress}}/api/Author/by-name?name=Emily%20Johnson
Accept: application/json


###
GET {{BlogApi2_backend_HostAddress}}/api/Author/by-id/8
Accept: application/json

###
DELETE {{BlogApi2_backend_HostAddress}}/api/Blog
 Accept: application/json


###
GET {{BlogApi2_backend_HostAddress}}/api/Blog/32
 Accept: application/json